config/routes.rb
Rails.application.routes.draw do

root "products#index"

resources :products
get '/register', to: 'users#new', as: :register
get '/users/sign_in', to: 'sessions#new', as: :sign_in
delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out
resources :sessions, only: [:create]
resources :users


get '/confirm_cart', to: 'carts#show', as: :confirm_cart
get '/checkout', to: 'carts#index', as: :checkout
post '/carts', to: 'carts#add_to_cart', as: :add_to_cart
get '/carts/edit_cart', to: 'carts#edit', as: :edit_cart
patch '/edit_cart/:id', to: 'carts#update', as: :update_quantities
patch '/edit_cart', to: 'carts#update_shipping', as: :update_shipping
delete 'confirm_cart', to: 'carts#destroy', as: :remove_from_cart

resources :orders, only: [:create]

end

app/controllers/cart_controller.rb
class CartController < ApplicationController

    def add_to_cart
    cart_item = CartItem.find_by(user: current_user, product_id: params.require(:product_id))
      if cart_item
        cart_item.quantity += 1
        cart_item.save
        flash[:notice] = "#{cart_item.name} has successfully been added to your cart (#{cart_item.quantity})"
        redirect_to products_path 
      else
        cart_item = CartItem.new(user: current_user, product_id: params.require(:product_id), quantity: 1)
        cart_item.save
        flash[:notice] = "#{cart_item.name} has successfully been added to your cart"
        redirect_to products_path 
      end
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def index
      @order = Order.new
      @cart_items = CartItem.where(user: current_user)
    end

    def show
      @cart_items = CartItem.where(user: current_user)
    end

    def add_to_cart
    cart_item = CartItem.find_by(user: current_user, product_id: params.require(:product_id))
      if cart_item
        cart_item.quantity += 1
        cart_item.save
        flash[:notice] = "#{cart_item.name} has successfully been added to your cart (#{cart_item.quantity})"
        redirect_to products_path 
      else
        cart_item = CartItem.new(user: current_user, product_id: params.require(:product_id), quantity: 1)
        cart_item = choose_default_shipping(cart_item)
        cart_item.save
        flash[:notice] = "#{cart_item.name} has successfully been added to your cart"
        redirect_to products_path 
      end
    end

    def update
        @cart_item = CartItem.find(params[:id])
        if params[:cart_item][:quantity].to_i == 0
          @cart_item.destroy
          flash[:notice] = "Item has successfully been removed from your cart"
          redirect_to confirm_cart_path
        else 
          if @cart_item.update(quantity: params[:cart_item][:quantity])
            flash[:notice] = "#{@cart_item.name} has successfully been updated"
            redirect_to confirm_cart_path
          else
          end
        end
    end

    def update_shipping
      shipping_option = ShippingOption.find_by(id: params[:shipping_option_id])
      current_user.cart_items.update_all(shipping_option_id: shipping_option.id)
      redirect_to confirm_cart_path
    end


private

    def cart_item_params
      params.require(:cart_item).permit(:id, :quantity)
    end

    def choose_default_shipping(cart_item)
      if current_user.cart_items.none?
        if current_user.member_plus
          cart_item.shipping_option_id = 1
        else
           cart_item.shipping_option_id = 4
        end
      else
        cart_item.shipping_option_id = current_user.cart_items.first.shipping_option_id
      end
      cart_item
    end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/carts/_cart.html.erb
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
          </h4>
          <ul class="list-group mb-3">
            <% @cart_items.each do |item| %>            
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0"><%= item.name%></h6>
                  <small class="text-muted"><%= item.description.truncate (40)%></small>        
                </div>
                <span class="text-muted">$<%= item.total_product_price %> (<%=item.quantity%>)</span>
              </li>    
            <% end %>
          </ul>

          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Order Summary</span>
          </h4>
          <ul class="list-group mb-3">            
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Shipping & Handling</h6>
                  <% if current_user.member_plus %>
                  <small class="text-muted">2 Day Shipping</small>        
                </div>
                <span class="text-muted">$2.99</span>
                  <% else %>
                  <small class="text-muted">5-7 Day Shipping</small>        
                </div>
                <span class="text-muted">$5.99</span>
              </li>    
                <% end %>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Total:</h6>    
                </div>
                <span class="text-muted">$<%=current_user.total_cart_value%></span>
              </li>   
          </ul>

app/views/carts/_checkout_cart.html.erb
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
          </h4>
          <ul class="list-group mb-3">
            <% @cart_items.each do |item| %>            
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0"><%= item.name%></h6>
                  <small class="text-muted"><%= item.description.truncate (40)%></small>        
                </div>
                <span class="text-muted">$<%= item.total_product_price %> (<%=item.quantity%>)</span>
              </li>    
            <% end %>
          </ul>
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Order Summary</span>
          </h4>
          <ul class="list-group mb-3">
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Total Item Value:</h6>    
                </div>
                <span class="text-muted">$<%=number_with_precision(current_user.total_item_value, precision: 2)%></span>
              </li>          
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Shipping & Handling:</h6>
                  <small class="text-muted"><%=current_user.cart_items.first.option%></small>      
                </div>
                <span class="text-muted">$<%=number_with_precision(current_user.total_shipping_cost, precision: 2)%></span>
              </li>
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">Final Cost:</h6>    
                </div>
                <span class="text-muted">$<%=number_with_precision(current_user.final_cost, precision: 2)%></span>
              </li>      
          </ul>

app/views/carts/_checkout_form.html.erb
<%= form_for :order, url: '/orders', data: {turbo: false} do |f| %>
  <h2> Shipping </h2>

    <div class='row g-3'>
      <div class='col-6'>
        <%= f.label :firstname, 'First name', class: 'form-label'%>
        <%= f.text_field :firstname, class: 'form-control mb-3', required: true%>
      </div>

      <div class='col-6'>
        <%= f.label :lastname, 'Last name', class: 'form-label' %>
        <%= f.text_field :lastname, class: 'form-control mb-3', required: true%>
      </div>   

      <div class='col-12'>
        <%= f.label :email, class: 'form-label' %>
        <%= f.email_field :email, placeholder: 'email@example.com', class: 'form-control mb-3', required: true%>
      </div>

      <div class='col-12'>
        <%= f.label :address, class: 'form-label' %>
        <%= f.text_field :address, class: 'form-control mb-3', required: true%>
      </div>

      <div class='col-md-5'> 
        <%= f.label :country, class: 'form-label' %> <br>
        <%= f.country_select :country, priority_countries = ["United States"], options = {}, html_options = {:class => "form-select mb-3"}%>
      </div>

      <div class='col-md-4'>
        <%= f.label :state, class: 'form-label' %>
        <%= f.text_field :state, placeholder: 'OH', class: 'form-control',
            required: true,
            pattern: '((A[LKSZR])|(C[AOT])|(D[EC])|(F[ML])|(G[AU])|(HI)|(I[DLNA])|(K[SY])|(LA)|(M[EHDAINSOT])|(N[EVHJMYCD])|(MP)|(O[HKR])|(P[WAR])|(RI)|(S[CD])|(T[NX])|(UT)|(V[TIA])|(W[AVIY]))'%>
            <small class="text-muted">Valid state abbreviation required</small>
      </div>

      <div class='col-md-3'>
        <%= f.label :zipcode, class: 'form-label' %>
        <%= f.number_field :zipcode, class: 'form-control mb-3', required: true%>
      </div>
    </div>


    <h2> Payment </h2>

    <div class='row gy-3'>

      <div class='col-md-6'>
        <%= f.label :ccname, 'Name on card', class: 'form-label'%>
        <%= f.text_field :ccname, class: 'form-control', required: true%>
        <small class="text-muted">Full name as displayed on card</small>
      </div>

      <div class='col-md-6'>
        <%= f.label :ccnumber, 'Credit card', class: 'form-label' %>
        <%= f.number_field :ccnumber, class: 'form-control',
            required: true,
            minimum: 16,
            maximum: 16,
            oninvalid: "this.setCustomValidity('entry must be 16 characters')"%>
      </div>

      <div class='col-md-3'>
        <%= f.label :expiration, 'Expiration date', class: 'form-label'%>
        <%= f.date_select :expiration,
            {discard_day: true, 
            use_month_numbers: true, 
            start_year: Date.today.year, 
            end_year: (Date.today.year+15),
            order: [:month, :year]},
            class: 'form-select mb-3',
            required: true%>
      </div>

      <div class='col-md-3'>
        <%= f.label :cvv, 'CVV', class: 'form-label'%>
        <%= f.text_field :cvv, class: 'form-control mb-3', required: true%>
      </div>
    </div>

      <%= f.submit :Checkout, class: 'btn btn-primary'%>

    <% end %>

app/views/carts/_confirm_cart.html.erb
  <div class="col-lg order-md-2 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
      <span class="text-muted">Confirm cart</span>
    </h4>
    <ul class="list-group mb-3">
      <% @cart_items.each do |item| %>            
        <li class="list-group-item d-flex justify-content-between lh-condensed">
          <div>
            <h6 class="my-0"><%= item.name%></h6>
            <small class="text-muted"><%= item.description.truncate (100)%></small>        
          </div>
          <span class="text-muted">$<%= item.total_product_price %>
            <%= form_for item, url: update_quantities_path(id: item) do |form| %>                    
              <%= form.select :quantity, (0..99), :class => 'form-select'%>
              <%= form.submit "Update", :class => 'btn btn-secondary btn-sm' %>                                   
            <% end %>
          </span>
        </li>     
      <% end %>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Total Item Value:</h6>    
        </div>
        <span class="text-muted">$<%=number_with_precision(current_user.total_item_value, precision: 2)%></span>
      </li>
      <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
          <h6 class="my-0">Estimated Shipping:</h6>  
        </div>
          <span class="text-muted">$<%=number_with_precision(current_user.total_shipping_cost, precision: 2)%></span>
      </li>
    </ul>
  </div>

app/views/carts/_confirm_shipping.html.erb
<div class="order-md-2 mb-4">
        
    <% if current_user.member_plus %>
        <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Confirm shipping</span>
        </h4>
        <%= form_with url: update_shipping_path, method: :patch, data: {turbo: false} do |f| %>
            <%= f.select :shipping_option_id, options_for_select([['Member Plus: 2-Day Free', 1],['Member Plus: Overnight (1.99/Item)', 2]], current_user.cart_items.first.shipping_option_id), {}, {class: "form-select mb-3"}%>
            <%= f.submit 'Update', class: 'btn btn-primary' %>
        <% end %>
    <% end %>
</div>

app/views/carts/index.html.erb
<div class='container'>
    <% if flash[:notice]%>
        <div class="alert alert-danger" role="alert">
            <%= flash[:notice] %>
        </div>
    <%end%>

    <div class='row g-5'>
        <div class='col-md-5 col-lg-4 order-md-last'>
            <%= render 'carts/checkout_cart', order: @order, cart_items: @cart_items %>
        </div>

        <div class='col-md-7 col-lg-8'>
            <%= render 'carts/checkout_form', order: @order, cart_items: @cart_items %>
        </div>
    </div>
</div>

        

app/views/carts/show.html.erb
<% if flash[:notice]%>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
<%end%>

<% if @cart_items.any? %>
    <div class='container-fluid'>
        <%= render 'confirm_shipping' %>
        <%= render 'confirm_cart' %>
        <%= link_to 'Proceed to Checkout', checkout_path, :class=>"btn btn-primary me-md-2" %>
    </div>
<% else %>
<p> Your cart is currently empty </p>
<%= link_to 'Return to Products', root_path, :class=>"btn btn-primary me-md-2" %>
<% end %>