config/routes.rb
Rails.application.routes.draw do

root "products#index"

resources :products
get '/register', to: 'users#new', as: :register
get '/users/sign_in', to: 'sessions#new', as: :sign_in
delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out
resources :sessions, only: [:create]
resources :users


get '/confirm_cart', to: 'carts#show', as: :confirm_cart
get '/checkout', to: 'carts#index', as: :checkout
post '/carts', to: 'carts#add_to_cart', as: :add_to_cart
get '/carts/edit_cart', to: 'carts#edit', as: :edit_cart
patch '/edit_cart/:id', to: 'carts#update', as: :update_quantities
patch '/edit_cart', to: 'carts#update_shipping', as: :update_shipping
delete 'confirm_cart', to: 'carts#destroy', as: :remove_from_cart

resources :orders, only: [:create]

end

app/models/product.rb
class Product < ApplicationRecord

has_many :cart_items
has_many :order_items


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    skip_before_action :authenticate!
    
    def index
        @products = Product.all
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
 <h1 class="text-center mb-5">Greg's Shop</h1>

    <div class="row justify-content-md-center">
    <% if flash[:notice]%>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
    <%end%>
      <% @products.each do |item| %>
        <div class="card mb-3 mx-1 col-3" style="width: 18rem;">
          <div class="card-body">
            <h4 class="card-title text-center"> <%= item.name %> </h4>
            <%= image_tag item.image_location, :class=>"img-thumbnail mb-3"%>
            <p class="card-subtitle  mb-2 text-muted text-decoration-line-through">List Price $<%= item.list_price %><p>
            <p class="card-subtitle fst-italic mb-2">Our Price $<%= item.our_price %><p>
            <p class="card-text fw-light"><%= item.description.truncate(200, separator: " ") %></p>
            <%= button_to "Add to Cart", add_to_cart_path, :class=>"btn btn-secondary btn-sm", params:{product_id: item.id}%>
          </div>
        </div>
      <% end %>
    </div>