config/routes.rb
Rails.application.routes.draw do

root "products#index"

resources :products
get '/register', to: 'users#new', as: :register
get '/users/sign_in', to: 'sessions#new', as: :sign_in
delete '/users/sign_out', to: 'sessions#destroy', as: :sign_out
resources :sessions, only: [:create]
resources :users


get '/confirm_cart', to: 'carts#show', as: :confirm_cart
get '/checkout', to: 'carts#index', as: :checkout
post '/carts', to: 'carts#add_to_cart', as: :add_to_cart
get '/carts/edit_cart', to: 'carts#edit', as: :edit_cart
patch '/edit_cart/:id', to: 'carts#update', as: :update_quantities
patch '/edit_cart', to: 'carts#update_shipping', as: :update_shipping
delete 'confirm_cart', to: 'carts#destroy', as: :remove_from_cart

resources :orders, only: [:create]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Greg's Shop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><%= link_to 'Home', root_path, :class=>"nav-link px-2 link-secondary"%></li>
        <li><%= link_to 'Checkout', confirm_cart_path, :class=>"nav-link px-2 link-secondary"%></li>
      </ul>

      <div class="col-md-3 text-end">
      <% if current_user %>
        <div class='item'>
         <p> Logged in as <%= current_user.username %></p>
         </div>
         <div class='item'>
          <%= link_to 'Logout', sign_out_path, method: :delete, :class=>"btn btn-primary"%>
         </div>
        <% else %>
          <div class="btn-group" role="group">
            <div class ='item'>
            <%= link_to 'Login', sign_in_path, :class=>"btn btn-primary me-md-2"%>
            </div>
            <div class ='item'>
            <%= link_to 'Sign-up', register_path, :class=>"btn btn-outline-primary me-md-2"%>
            </div>
          </div>
        <% end %>
    </div>
      </div>
    </header>
  </div>

  
  <div class = "container">
    <%= yield %>
  </div>
</html>